Go back to [STAT545A home](current.html)

Homework #5 Visualize anything with `ggplot2` 
========================================================

> Follow the [existing homework submission instructions](hw00_instructions.html). By 9:30am Monday Octber 7, be prepared to share your links via a Google doc.

  * Start with the Gapminder data as provided in [`gapminderDataFiveYear.txt`](http://www.stat.ubc.ca/~jenny/notOcto/STAT545A/examples/gapminder/data/gapminderDataFiveYear.txt) __or use something else!__
    - See threads on our [Google Group](https://groups.google.com/forum/#!forum/stat545a_2013) for our crowd-sourced suggestions for other datasets.
  * Make at least two figures using `ggplot`:
    - Include at least one stripplot-type of figure: one quantitative and one categorical variable. Bring in some extra information, for example by superposing groups, facetting (aka multi-panel conditioning), and/or overlaying, e.g. summary statistics.
    - Include at least one scatterplot: two quantitative variables. Do extras, e.g. superposing groups, facetting, overlaying with a fitted or external model.
  * Goals to shoot for:
    - If you continue to work with the Gapminder data, push yourself to make a plot we have not seen before. For example, do something that `ggplot2`'s flexible layering system allows that is impossible/hard in `lattice`.
    - If you continue to work with the Gapminder data, do a nice direct comparison between `lattice` and `ggplot2` code and figure result. Compare and contrast.
    - If you work with a new dataset ... good for you! Introduce it properly, e.g. number of observations, the variables, what is the point.
  * Write up with R Markdown.
    - Include a narrative, written in English prose. Don't *just* show code and results.
    - Expose your code, i.e. use `echo = FALSE` very sparingly.
  * DUE: Before class begins 9:30am Monday October 7.
    - Compile into an HTML report. Follow the naming convention. Publish the HTML report on the web somewhere, such as on RPubs. Make the slug follow the naming convention.
    - Publish the R Markdown file as a Gist. Follow the naming convention.
    - Share your links by editing the Google doc mentioned above.
 
### Student work on HW 4. *I'm leaving these links here in case you want to look around and as placeholders for HW 5.*

  * attali-dea [source](https://gist.github.com/daattali/6847430#file-stat545a-2013-hw05_attali-dea-rmd) | [report](http://rpubs.com/daattali/stat545a-2013-hw05_attali-dea) **uses ggplot’s colour brewer**
  * baik-jon [source](https://gist.github.com/jonnybaik/6863975#file-stat545a-2013-hw05_baik-jon-rmd) | [report](http://rpubs.com/jonnybaik/stat545a-2013-hw05_baik-jon)
  * bolandnazar-moh [source](https://gist.github.com/ArephB/6761239#file-stat545a-2013-hw04_bolandnazar-moh-rmd) | [report](http://rpubs.com/aref/stat545a-2013-hw04_bolandnazar-moh)
  * brueckman-chr EDIT HERE
  * chu-jus [source](https://gist.github.com/JustinChu/6869757#file-stat545a-2013-hw05_chu-jus-rmd) | [report](http://rpubs.com/cjustin/stat545a-2013-hw05_chu-jus)
  * Zachary Daly: [source](https://gist.github.com/ZDaly/6863685#file-stat545a-2013-hw05_daly-zac-rmd) | [report](http://rpubs.com/Zdaly/stat545a-2013-hw05_daly-zac)
  * dinsdale-dan [source](https://gist.github.com/danieldinsdale/6859543#file-stat545a-2013-hw05_dinsdale-dan-rmd) | [report](http://rpubs.com/danieldinsdale/stat545a-2013-hw05_dinsdale-dan)
  * gao-wen [source](https://gist.github.com/sibyl229/6864753#file-stat545a-2013-hw05_gao-wen-rmd) | [report](http://rpubs.com/less/stat545a-2013-hw05_gao-wen)
  * Matthew Gingerich: [source](https://gist.github.com/MattGingerich/6866066#file-stat545a-2013-hw05_gingerich-mat-rmd) | [report](http://rpubs.com/majugi/stat545a-2013-hw05_gingerich-mat)
  * hu-yum [source](https://gist.github.com/smilecat/6870853#file-stat545a-2013-hw05_hu-yum-rmd) | [report](http://rpubs.com/smilecat/stat545a-2013-hw05_hu-yum)
  * jewell-sea [source](https://gist.github.com/jewellsean/867bebb18dac08a0e4bc#file-stat545a-2013-hw05_jewell-sea-rmd) [report](http://rpubs.com/jewellsean/stat545a-2013-hw05_jewell-sea)
  * johnston-reb [source](https://gist.github.com/rebjoh/6870958#file-stat545a-2013-hw05_johnston-reb-rmd) | [report](http://rpubs.com/rljohn/stat545a-2013-hw05_johnston-reb)
  * mahdiar khosravi [source](https://gist.github.com/Mahdiark/6863914#file-stat545a-2013-hw05_khosravi-mah-rmd) | [report](http://rpubs.com/mahdiar/stat545a-2013-hw05_khosravi-mah)
  * Wooyong Lee: [source](https://gist.github.com/folias/6869843#file-stat545a-2013-hw05_lee-woo) | [report](http://rpubs.com/folias/stat545a-2013-hw05_lee-woo)
  * liao-wei: [source](https://gist.github.com/feiba/6863586#file-stat545a-2013-hw05_liao_wei-rmd) | [report](http://rpubs.com/winson/stat545a-2013-hw05_liao_wei)
  * ma-hui [source](https://gist.github.com/horsehuiting/6863220#file-stat545a-2013-hw05_ma-hui-rmd) | [report](http://rpubs.com/Huiting/stat545a-2013-hw05_ma-hui)
  * meng-viv [source](https://gist.github.com/vmeng321/6749120#file-stat545a-2013-hw04_meng-viv-rmd) | [report](http://rpubs.com/vmeng321/stat545a-2013-hw04_meng-viv)
  * mohd abul basher-abd [source](https://gist.github.com/atante/6865308#file-stat545a-2013-hw05_mohd-abul-basher-abd-rmd) | [report](http://rpubs.com/meitantei/stat545a-2013-hw05_mohdabulbasher-abd)  
  * ni-jac [source](https://gist.github.com/jacknii/6857193#file-stat545a-2013-hw05_ni-jac-rmd) | [report](http://rpubs.com/jackni/stat545a-2013-hw05_ni-jac)
  * Christian Okkels [source](https://gist.github.com/cbokkels/6804979#file-stat545a-2013-hw05_okkels-chr-rmd) | [report](http://rpubs.com/cbokkels/stat545a-2013-hw05_okkels-chr)
  * Greg Owens: [source](https://gist.github.com/opsin/6862895#file-stat545a-2013-hw05_owens-greg-rmd) | [report](http://rpubs.com/opsin/stat545a-2013-hw05_owens-greg)
  * Mina Park: [source](https://gist.github.com/parkm87/6870037#file-stat545a-2013-hw05_park-min-rmd) | [report](http://rpubs.com/parkm87/stat545a-2013-hw05_park-min)
  * spencer-nei [source](https://gist.github.com/neilspencer/6864836#file-stat545a-2013-hw05_spencer-nei-rmd) | [report](http://rpubs.com/neil_spencer/stat545a-2013-hw05_spencer-nei)
  * wang-ton [source](https://gist.github.com/yzhxh/6864031#file-stat545a-2013-hw05_wang-ton-rmd) | [report](http://rpubs.com/yzhxh/stat545a-2013-hw05_wang-ton)
  * Leah Weber: [source](https://gist.github.com/lweber21/6847194#file-stat545a-2013-hw05_weber-lea-rmd) | [report](http://rpubs.com/lweber21/stat545a-2013-hw05_weber-lea)
  * woollard-geo [source](https://gist.github.com/geoffwoollard/6862144#file-stat545a-2013-hw05_woollard-geo-rmd) | [report](http://rpubs.com/gwoollard/stat545a-2013-hw05_woollard-geo)
  * xue-xinxin [source](https://gist.github.com/xxue/6862107#file-stat545a-2013-hw05_xue-xinxin-rmd) | [report](http://rpubs.com/xxue/stat545a-2013-hw05_xue-xinxin) 
  * yuen-ama [source](https://gist.github.com/amandammor/6856787#file-stat545a-2013-hw05_yuen-ama) | [report](http://rpubs.com/amandammor/stat545a-2013-hw05_yuen-ama)
  * zhang-yim [source](https://gist.github.com/zym268/6862697#file-stat545a-2013-hw05_zhang-yim)| [report](http://rpubs.com/zym268/STAT545A-2013-hw05_zhang-yim)
  * zhang-jon [source](https://gist.github.com/jzhang722/6847642#file-stat545a-2013-hw05_zhang-jon) | [report](http://rpubs.com/jzhang722/stat545a-2013-hw05_zhang-jon)
  * zhang-yif [source](https://gist.github.com/dora7870/6863814#file-stat545a-2013-hw05_zhang-yif-rmd) | [report](http://rpubs.com/dora7870/stat545a-2013-hw05_zhang-yif)
  * zhang-jin [source](https://gist.github.com/0527zhangjinyuan/6871031#file-stat545a-2013-hw05_zhang-jin-rmd) | [report](http://rpubs.com/zhangjinyuan/stat545a-2013-hw05_zhang-jin)
  * inskip-jes [source](https://gist.github.com/jinskip/6871151#file-stat545a-2013-hw05_inskip-jes) | [report](http://rpubs.com/jinskip/stat545a-2013-hw05_inskip-jes)
  * liu-yan [source](https://gist.github.com/swallow0001/e0785a7a979850dff731#file-ggplot) | [report](http://rpubs.com/swallow0001/Stat545a-2013-hw5-Liu)
  * haraty-mon EDIT HERE
  * yuen-mac [source](https://gist.github.com/myuen/6862189#file-stat545a-2013-hw05_yuen-mac-rmd) | [report](http://rpubs.com/myuen/stat545a-2013-hw05_yuen-mac)

  

<div class="footer">
This work is licensed under the  <a href="http://creativecommons.org/licenses/by-nc/3.0/">CC BY-NC 3.0 Creative Commons License</a>.
</div>